repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: double-quote-string-fixer
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.6.4
    hooks:
    - id: docformatter
      args: ['--wrap-summaries=100', '--wrap-descriptions=100']
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/csachs/pyproject-flake8
    rev: v6.0.0.post1
    hooks:
    - id: pyproject-flake8
